# Generated by Django 6.0 on 2025-12-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_alter_choice_options_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='polls.question')),
            ],
            options={
                'verbose_name': 'Статистика опроса',
                'verbose_name_plural': 'Статистики опросов',
            },
        ),
    ]
